In [14]:
import numpy as np
import pandas as pd

In [3]:
a = np.array([2,3,4])

In [4]:
a

array([2, 3, 4])

In [5]:
b = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])

In [6]:
b


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [7]:
b.ndim

2

In [8]:
b.shape

(3, 3)

In [9]:
b.size

9

In [10]:
a + b

array([[ 3,  5,  7],
       [ 7,  9, 11],
       [11, 13, 15]])

In [11]:
a = np.array([2,3,])

In [19]:
pd.Series(data={'John': 21, 'Jane': 25, 'Carl': 30})
#x = pd.Series(data={'John': 21, 'Jane': 25, 'Carl': 30}) if you want to assing it to a vairiable

In [21]:
pd.DataFrame( {'col_1': [1, 2], 'col_2': [3, 4]} )


col_1  col_2
0      1      3
1      2      4

In [27]:
d = {'col1': [1, 2], 'col2': [3, 4],'col3': [5, 6]}
df = pd.DataFrame(data=d)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [26]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(my_array, columns=['col1', 'col2', 'col3'])
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [28]:
df.head(3)

col1  col2  col3
0     1     3     5
1     2     4     6

In [29]:
df['col2']

0    3
1    4
Name: col2, dtype: int64

In [30]:
df.shape


(2, 3)

In [31]:
df.tail(2)

col1  col2  col3
0     1     3     5
1     2     4     6

In [34]:
df1 = pd.DataFrame(my_array, index=['jellies', 'lollipop', 'gum'], columns=['blue', 'red', 'yellow'])

In [38]:
df1.loc['gum']

blue      7
red       8
yellow    9
Name: gum, dtype: int32

In [39]:
df1.loc[['jellies','gum']]

blue  red  yellow
jellies     1    2       3
gum         7    8       9

In [43]:
df1.iloc[0]

blue      1
red       2
yellow    3
Name: jellies, dtype: int32

In [42]:
df1


blue  red  yellow
jellies      1    2       3
lollipop     4    5       6
gum          7    8       9